#13 [feat] Employer Controller 구현
SOPT-TEAM9-Carrot/Carrot-SERVER pull request #15
Opened 2023-05-18 14:07 UTC by 2zerozu

## ✒️ 관련 이슈번호

- Closes #13

## 🔑 Key Changes

1. `exception` 추가했습니다! (`ApiException`, `BadRequestException`, `NotFoundException`)
2. `ControllerExceptionAdvice` 추가했습니다

## 📢 To Reviewers

# 나, 이빵주. 해냈다. 유서린. 최고. 계대환. 짱.

2023-05-18 16:48 UTC, daehwan2da requested changes
### (1)
JsonResponse 가 잘못구성되어진것같네요

질문) JsonResponse.error(..) 이렇게 client 에 응답되면 body 의 status 필드에는 400이라고 남겠지만, header 의 status 는 어떻게될까요?

참고) ResponseEntity 찾아보세요
- https://thalals.tistory.com/268

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/common/ControllerExceptionAdvice.java
> +public class ControllerExceptionAdvice {
에러 응답 다 바꾸는게 좋을것같아요~
ResponseEntity 참고

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/EmployerController.java
> +    @GetMapping
@ GetMapping 뒤에 어떤 path 에 대한 정보가 없는데,
@ PathVariable Long userId 이렇게 두면, 어떤 값으로 바인딩되지 몰라서 정상적으로 동작하지 않겠네요~
```suggestion
    @GetMapping("/{userId}")
```

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/EmployerController.java
> +        if (!("0".equals(authorization) || "1".equals(authorization))) {
api 명세서를 지금 확인했는데,
header 의 Authorization 에 userId 를 담는 형식으로 구성했네요
동작은 하지만, 정석에서는 어긋나는 방식입니다~

userId 는 path variable 혹은 query param 에서만 받는게 좋아요~

Authorization header
[docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization)
[blog](https://archijude.tistory.com/457)

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/dto/response/EmployerResponseDto.java
> +public class EmployerResponseDto {
@ NoArgsConstructor 추가해야할겁니다

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/dto/response/EmployerResponseDto.java
> +public class EmployerResponseDto {
이유는 json parsing 과 reflection 을 공부해보면좋은데, 어려울수 있으니, 그냥 spring 에서 이런 data class 같은것 만들때 기본생성자는 필수로 넣는다라고 생각해도 좋아요

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerService.java
>  public interface EmployerService {
interface 만들고 impl 로 구현하는 방식인것같은데, 최근 Spring 버전에서는 이런 방식안써도 괜찮아요~
- 옛날에 interface 기반으로 proxy 가 생성되는 방식이 있었는데.. 어려운 내용이지만.. spring으로 취업할라면 알아야하는.. ㅎ

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerServiceImpl.java
> +        if (size < 0) {
size 를 controller 에서 음수인지 확인해보는건 어떨까요
안드로이드에서 layer 나누어서 data, persentation 이렇게 나누듯이, 서버도 layering 이 매우 중요한데요,
이런 client 가 입력한 interface 와 관련된 처리는 controller layer 에서 처리하고, Service 는 비즈니스 로직에 집중하는게 좋을것같네요~

2023-05-18 16:48 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerServiceImpl.java
> +                user.getDegree(),
java 는 kotlin 에 비해서 null 에대한 자유도가 높아서, NPE (NullPointerException) 에 예민한데요,
지금 userEntity 에 만약 degree 가 null 인 경우, NPE 가 발생할 수 있겠네요
(EmployerResponseDto 에서 degree 필드가 float, primitive type 이라 null 불가)

삼항연산자를 활용해보세요
```suggestion
                user.getDegree() == null ?  0 : user.getDegree(),
```

2023-05-18 16:48 UTC, daehwan2da requested changes
### (1)
JsonResponse 가 잘못구성되어진것같네요

질문) JsonResponse.error(..) 이렇게 client 에 응답되면 body 의 status 필드에는 400이라고 남겠지만, header 의 status 는 어떻게될까요?

참고) ResponseEntity 찾아보세요
- https://thalals.tistory.com/268

2023-05-18 16:49 UTC, daehwan2da commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/EmployerController.java
> +    @GetMapping
음 하나만 있을때는 자동으로 바인딩이되나.. ㅋㅋ 이건 확실하지 않네요
근데 저렇게 명시해주는게 좋아요

2023-05-18 16:50 UTC, 2zerozu commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/EmployerController.java
> +    @GetMapping
`@GetMapping("/{userId}/reviewrs")` 이렇게 적으려고합니다요

2023-05-18 16:55 UTC, 2zerozu commented on carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/dto/response/EmployerResponseDto.java
> +public class EmployerResponseDto {
오 final때문에 하이라이트 쳐졌던거 없어졌어요 감사합니다

2023-05-19 05:19 UTC, SeorinY approved these changes
수고햇어어어ㅓㅓㅓㅓ

2023-05-19 05:19 UTC, SeorinY approved these changes
수고햇어어어ㅓㅓㅓㅓ

2023-05-19 05:26 UTC, merged